### ISSUE TITLE
[SOLUTION] Dynamic Trees Compatibility

### ISSUE THREAD

**Issue by Explode007** [JDKDigital/treetap#2]
Hi LobsterJohn!

I am making my own custom terrafirmacraft + tech modpack and I am utilizing dynamic trees. However, your mod doesn't work with dynamic trees. This is because the checks for determining a valid tree don't apply on Dynamic Trees since they have no 'branch_direction'. However, I cloned the repo and created a fix where determining if the radius is 8 (max) then you can tap it. This simple check fulfills the need of a tree being alive and grown since when you break the tree itself you get actual logs. And as you can see in the image below, it works.

Let me know if you are interested! the code is simple and I can submit a PR so its easy to merge (currently PR's are disabled)

![image](https://github.com/user-attachments/assets/e112a887-2980-408d-a77f-6d38381ce084)

**Comment by JaisDK** [comment]
Nice, of course I'm interested. PRs should not be disabled, did you fork the project first?

**Comment by SamuelRUM** [comment]
No, thats probably on me, I cloned as I've never really worked on a project thats 'closed' on github. Im getting on my computer in a sec and ill see if I can figure it out.

**Comment by Explode007** [comment]
No, thats probably on me, I cloned as I've never really worked on a project thats 'closed' on github. Im getting on my computer in a sec and ill see if I can figure it out.

I was also going to say that i found the repo via one of your other popular mods that had a link to your github, at the moment treetap does not have the source tab on curse.

**Comment by Explode007** [comment]
#3 PR
